### PR TITLE
Prepare 0.5.0

### LINKED ISSUE #44: 0.5.0
I am done with my intended changes, I wanted to get `try_flat_map_ok/err` in there aswell but it was a bit more fiddly than I  had the patience to finish within a reasonable time frame so I will have to leave it for now.

So, time to get 0.5.0 released @matthiasbeyer ?

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is the preparation for the 0.5.0 release of the resiter crate.

Closes #44

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@johlrogge You notably contributed in the last time, maybe you want to have a look. I kept the changelog rather minimal... should we expand on this? If yes, what?

**Review by johlrogge — APPROVED** [review]
Looks right. 

Specifically the filtermethods that were added were `try_filter_ok` and `try_filter_map_ok`. Both have in common that the filterfunction can itself return a result allowing the `?` operator to be used within the filter lambda.

the `try_` prefix is a new naming convention that perhaps should be mentioned. It is a bit special in that the `try_`-methods do not return a `Result' as one might expect, but the functions used to filter or filter_map returns a Result.

I plan to add more doc tests and I also plan to add `try_filter_err`and `try_filter_map_err` for completeness, But that could be done in a later release.

Also, I noted that the prelude-module does not expose all traits in this crate, that should be fixed too, but perhaps in a later release.

**Comment by matthiasbeyer** [comment]
> I plan to add more doc tests and I also plan to add try_filter_errand try_filter_map_err for completeness, But that could be done in a later release.
> 
> Also, I noted that the prelude-module does not expose all traits in this crate, that should be fixed too, but perhaps in a later release.

I am fine with adding both these things in the 0.5.0 release, if you want! There's no need to hurry with the release! I'd love to see more patches from you! :heart:

**Comment by johlrogge** [comment]
Great!

I'll let you know when I'm done.

Also, for a later release I have some ideas for some breaking structural changes. I thought to maybe add issues for them so we can discuss them.

In a nutshell resiter has a lot of submodules which makes documentation on module-level pretty cumbersome and leaves documentation looking pretty bare. I would like to think a bit about how to make this situation better but I don't have a lot of experience building rust-crates.

11 Apr 2023 15:14:20 Matthias Beyer ***@***.***>:

**Comment by matthiasbeyer** [comment]
> I thought to maybe add issues for them so we can discuss them.

Yes please! :+1: 

> I would like to think a bit about how to make this situation better but I don't have a lot of experience building rust-crates.

Feel free to experiment! I am looking forward to your patches!

**Comment by matthiasbeyer** [comment]
@johlrogge Do you want some specific things to be named in the changelog? By now you should have a better overview than I have over what changed :laughing:

**Comment by johlrogge** [comment]
I can update the changelog after I have eaten :)

25 Apr 2023 13:29:33 Matthias Beyer ***@***.***>:

**Comment by matthiasbeyer** [comment]
bors merge

:tada:

**Comment by matthiasbeyer** [comment]
0.5.0 released. :tada:

**Pull request merged**
