### PR TITLE
rename filter_ok_and_then to try_filter_ok

### PR DESCRIPTION
**Pull request by johlrogge**
Thank you for an aweseom lib. I would really need the unreleased `filter_ok_and_then`-method. It was a bit difficult to find for me and while the signature of the predicate function makes it clear t is not the case the name of the function suggests that the function will throw away everything that is not an ok and then do something with the remaining oks. 

I thought `try_filter_ok` was a bit more clear but I admit that I would expect the returned value to be a `Result<Iterator<T>, E>`. 

Perhaps `try_filter_ok` is clear enough and can be merged, or this is the start of a discussion that leads to a release of the above mentioned functionality.

I'd be happy to help in any way I can to get to a 0.5 soon

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Hi!
Thanks for your PR, it is highly appreciated! I am fine with these changes, but CI fails. Please fix up the errors, and I'll merge then! :wink:

**Comment by johlrogge** [comment]
I saw that they failed. Will tend to that in a moment. Thank you.

20 Mar 2023 09:47:28 Matthias Beyer ***@***.***>:

**Comment by johlrogge** [comment]
I am a bit confused about how to fix the signed off line. Do I need to amend a certain commit or add a commit with a line like:
Signed-off-by: johlrogge <joakim.ohlrogge@agical.se> 

?

**Comment by matthiasbeyer** [comment]
What you do is you `git rebase origin/main -i` and squash all commits into one and then add the trailer there. Then you `git push <your remote> <your branch> -f`.

Make also sure to capitalize the first word and so on... :wink:

**Comment by johlrogge** [comment]
CI runs in my fork now. I hope everything is ok now.

**Comment by matthiasbeyer** [comment]
From what I see, this looks good now. Thanks for your contribution!

bors merge

**Pull request merged**
